### Get all facilities
GET http://localhost:3000/facilities/

### Get a facility by id
GET http://localhost:3000/facilities/65302331162e10b0dff5c6d0

### Create a facility
POST http://localhost:3000/facilities/
Content-Type: application/json

{
    "facilityName": "Facility 1",
    "facilityType": "retail",
    "operatingHours": {
        "start": "11:00",
        "end": "23:00"
    },
    "numberEmployees": "5",
    "numberShifts": "1",
    "numberDays": "5"
}

### Delete a facility
DELETE http://localhost:3000/facilities/6530236b162e10b0dff5c6d3

### Update the facility info
PATCH http://localhost:3000/facilities/653026ac162e10b0dff5c6da
Content-Type: application/json

{
    "facilityType": "hospital"
}

### Get all notifications
GET http://localhost:3000/notifications/


### Get a scbedule by id
GET http://localhost:3000/notifications/653026db162e10b0dff5c6e1


### Get all notification
GET http://localhost:3000/notifications/


### Create a noification
POST http://localhost:3000/notifications/
Content-Type: application/json

{
    "title": "Staff1 Availibility",
    "content": "Hey Staff1! Are available on Wednesday? Thank you."
   
}

### Delete a notification
DELETE http://localhost:3000/notifications/


### Update the notification info
PATCH http://localhost:3000/notifications/
Content-Type: application/json

{
    "content": "Hey Staff 1! Thank you for the response!"
}