

###
GET http://localhost:8080/facilities
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTczOWExOTgxMzNmMWE4NDU5ZDRhMjEiLCJpYXQiOjE3MDIwNzQ5MDcsImV4cCI6MTcwMjE2MTMwN30.3yDvu5Uu75uttYrel1kXKEzZWnNVh-RKo3YtUMmPvkQ

### Create a facility
POST http://localhost:8080/facilities/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTczOWExOTgxMzNmMWE4NDU5ZDRhMjEiLCJpYXQiOjE3MDIwNzQ5MDcsImV4cCI6MTcwMjE2MTMwN30.3yDvu5Uu75uttYrel1kXKEzZWnNVh-RKo3YtUMmPvkQ

{
    "facilityName": "Facility 2",
    "facilityType": "retail",
    "operatingHours": {
        "start": "11:00",
        "end": "23:00"
    },
    "numberShifts": 2
}

### Delete a facility
DELETE http://localhost:8080/facilities
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTczOWExOTgxMzNmMWE4NDU5ZDRhMjEiLCJpYXQiOjE3MDIwNzQ5MDcsImV4cCI6MTcwMjE2MTMwN30.3yDvu5Uu75uttYrel1kXKEzZWnNVh-RKo3YtUMmPvkQ


### Update the facility info
PATCH http://localhost:8080/facilities
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTczOWExOTgxMzNmMWE4NDU5ZDRhMjEiLCJpYXQiOjE3MDIwNzQ5MDcsImV4cCI6MTcwMjE2MTMwN30.3yDvu5Uu75uttYrel1kXKEzZWnNVh-RKo3YtUMmPvkQ

{
    "facilityType": "hospital",
    "facilityName": "f1"
}
