

### Get all facilities
GET http://localhost:8080/facilities
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTY3YjFjMGZhMWMzN2Q3Zjg4ZDcxZjAiLCJpYXQiOjE3MDEyOTk5MTEsImV4cCI6MTcwMTM4NjMxMX0.DNdcd_GuMqDsGSJrCQGtKKaRuiAScMI0l20Q1zEYi1I

### Get a facility by id
GET http://localhost:8080/facilities/65302331162e10b0dff5c6d0

### Create a facility
POST http://localhost:8080/facilities/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTY3YjFjMGZhMWMzN2Q3Zjg4ZDcxZjAiLCJpYXQiOjE3MDEyOTQ1MzEsImV4cCI6MTcwMTM4MDkzMX0.dZqyAgMS5pON_pHxSLXjZ_nDBKSHb6o4pz192ZB26jY

{
    "facilityName": "Facility 2",
    "facilityType": "retail",
    "operatingHours": {
        "start": "11:00",
        "end": "23:00"
    },
    "numberShifts": 2
}

### Delete a facility
DELETE http://localhost:8080/facilities/6530236b162e10b0dff5c6d3

### Update the facility info
PATCH http://localhost:8080/facilities/653026ac162e10b0dff5c6da
Content-Type: application/json

{
    "facilityType": "hospital"
}
