

### Get all notification
GET http://localhost:8080/notifications/
Authorization: Bearer eyJhbGciiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTczOWExOTgxMzNmMWE4NDU5ZDRhMjEiLCJpYXQiOjE3MDIwNzQ5MDcsImV4cCI6MTcwMjE2MTMwN30.3yDvu5Uu75uttYrel1kXKEzZWnNVh-RKo3YtUMmPvkQ


### Get a notification by id
GET http://localhost:8080/notifications/65739bc78133f1a8459d4a6d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTczOWExOTgxMzNmMWE4NDU5ZDRhMjEiLCJpYXQiOjE3MDIwNzQ5MDcsImV4cCI6MTcwMjE2MTMwN30.3yDvu5Uu75uttYrel1kXKEzZWnNVh-RKo3YtUMmPvkQ


### Create a noification
POST http://localhost:8080/notifications/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTczOWExOTgxMzNmMWE4NDU5ZDRhMjEiLCJpYXQiOjE3MDIwNzQ5MDcsImV4cCI6MTcwMjE2MTMwN30.3yDvu5Uu75uttYrel1kXKEzZWnNVh-RKo3YtUMmPvkQ

{
    "employeeId": "65739a958133f1a8459d4a2f",
    "message": "Hey Bob!"
}

### Delete a notification
DELETE http://localhost:8080/notifications/65738ed194ffd7661d26550f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTczOWExOTgxMzNmMWE4NDU5ZDRhMjEiLCJpYXQiOjE3MDIwNzQ5MDcsImV4cCI6MTcwMjE2MTMwN30.3yDvu5Uu75uttYrel1kXKEzZWnNVh-RKo3YtUMmPvkQ


### Update the notification info
PATCH http://localhost:8080/notifications/65739bc78133f1a8459d4a6d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTczOWExOTgxMzNmMWE4NDU5ZDRhMjEiLCJpYXQiOjE3MDIwNzQ5MDcsImV4cCI6MTcwMjE2MTMwN30.3yDvu5Uu75uttYrel1kXKEzZWnNVh-RKo3YtUMmPvkQ

{
    "message": "Hey Staff 1! Thank you for the response!"
}
