### Signup the new user
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
    "name": "Andy",
    "email": "cx2295@columbia.edu",
    "password": "12345"
}

### 
POST http://localhost:8080/auth/login 
Content-Type: application/json

{
    "email": "cx2295@columbia.edu",
    "password": "12345"
}
