

### Get all facilities
GET http://localhost:8080/facilities
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQ4NzFkN2NiZjhlYTA3MzJmZmQ3NTEiLCJpYXQiOjE2OTkzNzE3OTIsImV4cCI6MTY5OTQ1ODE5Mn0.U40K8QID8pqH3efSpMY9LZP5EweGsBfC24fFsF25A7k

### Get a facility by id
GET http://localhost:8080/facilities/65302331162e10b0dff5c6d0

### Create a facility
POST http://localhost:8080/facilities/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQ4NzFkN2NiZjhlYTA3MzJmZmQ3NTEiLCJpYXQiOjE2OTkzNzE3OTIsImV4cCI6MTY5OTQ1ODE5Mn0.U40K8QID8pqH3efSpMY9LZP5EweGsBfC24fFsF25A7k

{
    "facilityName": "Facility 2",
    "facilityType": "retail",
    "operatingHours": {
        "start": "11:00",
        "end": "23:00"
    },
    "numberEmployees": "5",
    "numberShifts": "1",
    "numberDays": "5"
}

### Delete a facility
DELETE http://localhost:8080/facilities/6530236b162e10b0dff5c6d3

### Update the facility info
PATCH http://localhost:8080/facilities/653026ac162e10b0dff5c6da
Content-Type: application/json

{
    "facilityType": "hospital"
}
