# [optional] the name appeared under "Actions/All workflows"
name: CI Workflow

# triggered on every push event
on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm ci

      - name: Run unit tests
        run: npm test

      - name: Archive unit test report
        uses: actions/upload-artifact@v3
        with:
          name: unittest-report
          path: reports/unittest-report.html
      
      - name: Archive coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: reports/coverage/

      - name: ESLint style check
        run: npm run lint

      - name: Archive ESLint style check report
        uses: actions/upload-artifact@v3
        with:
          name: style-check-report
          path: reports/style-check-report.html
